"""The RNG contract, three ways.

`docs/rng-contract.md` is the specification and `datasets/rng/vectors.json` is
the fixture the C# port is accepted against. A fixture generated by the code it
tests proves nothing on its own, so this checks three separate things:

1. **Known answers from outside this repo.** MT19937 seeded with 5489 has
   published first outputs. If those match, the core is the real algorithm and
   not merely self-consistent.
2. **The properties the contract states**, asserted directly -- draw counts,
   shuffle direction, the short-circuit, undo behaviour.
3. **The fixture**, replayed, plus a check that it is not stale.

See MARVEL-38; MARVEL-8 implements the same contract in C#.
"""

import json
import os
import unittest

# The `game.*` packages import each other circularly and only resolve once the
# `engine` package has been imported.
import engine  # noqa: F401  pylint: disable=unused-import

from engine.lib.mt19937 import N, UNDO_DEPTH, Mt19937
from engine.lib.random import Random

VECTORS = os.path.join("..", "datasets", "rng", "vectors.json")


def LoadVectors():
    with open(VECTORS, "r", encoding="utf-8") as handle:
        return json.load(handle)


class WordCounter:
    """Counts raw 32-bit draws, so tests can pin stream consumption.

    Restores the original on exit. `Random.rand` is a long-lived shared
    instance, so a counter left installed would nest inside the next one.
    """

    def __init__(self, rng):
        self.rng = rng
        self.words = 0
        self.original = rng.NextUInt32

        def Counted():
            self.words += 1
            return self.original()

        rng.NextUInt32 = Counted

    def Reset(self):
        used, self.words = self.words, 0
        return used

    def Restore(self):
        self.rng.NextUInt32 = self.original

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self.Restore()


def Sequence(length):
    return list(range(length))


class RngTestCase(unittest.TestCase):

    def Counter(self, rng):
        """A word counter that uninstalls itself when the test finishes."""
        counter = WordCounter(rng)
        self.addCleanup(counter.Restore)
        return counter


class TestPublishedKnownAnswers(RngTestCase):
    """External truth: these values do not come from this repository."""

    def test_the_reference_seed_matches_the_published_stream(self):
        # 5489 is MT19937's own default seed and these are its published first
        # outputs. Matching them says the core is genuine MT19937.
        rng = Mt19937(5489)

        self.assertEqual(
            [rng.NextUInt32() for _ in range(10)],
            [3499211612, 581869302, 3890346734, 3586334585, 545404204,
             4161255391, 3922919429, 949333985, 2715962298, 1323567403],
        )

    def test_seed_42_matches_what_numpy_produced(self):
        # The engine's previous production generator was numpy's legacy
        # RandomState. Its raw word stream is unchanged by MARVEL-38 -- only
        # the consumption layer moved -- so this pins that claim.
        rng = Mt19937(42)

        self.assertEqual(
            [rng.NextUInt32() for _ in range(6)],
            [1608637542, 3421126067, 4083286876, 787846414, 3143890026, 3348747335],
        )

    def test_seeding_uses_init_genrand_not_init_by_array(self):
        # The two seeding routines give completely different streams from the
        # same number. `init_genrand(1)` starts here.
        rng = Mt19937(1)

        self.assertEqual(rng.NextUInt32(), 1791095845)


class TestBoundedIntegers(RngTestCase):

    def test_results_stay_in_range(self):
        rng = Mt19937(42)
        for n in (1, 2, 3, 52, 1000):
            for _ in range(200):
                value = rng.NextBelow(n)
                self.assertGreaterEqual(value, 0)
                self.assertLess(value, n)

    def test_a_bound_of_one_still_consumes_a_word(self):
        # Not special-cased: short-circuiting would move the stream for every
        # draw after it. See `docs/rng-contract.md` section 2.
        rng = Mt19937(42)
        counter = self.Counter(rng)

        self.assertEqual(rng.NextBelow(1), 0)
        self.assertEqual(counter.Reset(), 1)

    def test_powers_of_two_never_reject(self):
        rng = Mt19937(42)
        counter = self.Counter(rng)

        for _ in range(50):
            rng.NextBelow(256)

        self.assertEqual(counter.Reset(), 50)

    def test_a_rejected_word_is_not_reused(self):
        # A bound of 3 masks to 0..3, so a raw word ending in 0b11 is rejected.
        # The next result must come from a fresh word, never from the rejected
        # one shifted or reused.
        rng = Mt19937(20260807)
        counter = self.Counter(rng)
        results = [rng.NextBelow(3) for _ in range(100)]

        self.assertTrue(all(0 <= value < 3 for value in results))
        # Rejection means strictly more words than draws, on this seed.
        self.assertGreater(counter.Reset(), 100)

    def test_the_full_32_bit_range_is_allowed(self):
        rng = Mt19937(42)

        self.assertEqual(rng.NextBelow(2**32), 1608637542)

    def test_an_impossible_bound_is_an_error(self):
        rng = Mt19937(42)

        with self.assertRaises(ValueError):
            rng.NextBelow(0)
        with self.assertRaises(ValueError):
            rng.NextBelow(2**32 + 1)


class TestShuffle(RngTestCase):

    def test_the_result_is_a_permutation(self):
        rng = Mt19937(42)
        items = Sequence(52)
        rng.Shuffle(items)

        self.assertEqual(sorted(items), Sequence(52))

    def test_it_consumes_one_draw_per_element_after_the_first(self):
        rng = Mt19937(42)
        counter = self.Counter(rng)
        rng.Shuffle(Sequence(10))

        # Nine draws, plus whatever rejection costs on this seed.
        self.assertGreaterEqual(counter.words, 9)

    def test_short_lists_consume_nothing(self):
        rng = Mt19937(42)
        counter = self.Counter(rng)

        rng.Shuffle([])
        rng.Shuffle([7])

        self.assertEqual(counter.Reset(), 0)

    def test_it_runs_downward(self):
        # Direction is part of the contract: upward Fisher-Yates gives a
        # different permutation from the same stream. Reproduce the downward
        # loop by hand against an independent generator and require a match.
        rng = Mt19937(42)
        items = Sequence(8)
        rng.Shuffle(items)

        expected = Sequence(8)
        by_hand = Mt19937(42)
        for i in range(len(expected) - 1, 0, -1):
            j = by_hand.NextBelow(i + 1)
            expected[i], expected[j] = expected[j], expected[i]

        self.assertEqual(items, expected)


class TestChoice(RngTestCase):

    def test_choice_returns_a_member(self):
        rng = Mt19937(42)
        sequence = Sequence(7)

        for _ in range(50):
            self.assertIn(rng.Choice(sequence), sequence)

    def test_an_empty_sequence_is_an_error(self):
        with self.assertRaises(ValueError):
            Mt19937(42).Choice([])

    def test_choosing_k_gives_k_distinct_members(self):
        rng = Mt19937(7)
        picked = rng.ChooseWithoutReplacement(Sequence(20), 5)

        self.assertEqual(len(picked), 5)
        self.assertEqual(len(set(picked)), 5)
        self.assertTrue(set(picked).issubset(set(Sequence(20))))

    def test_choosing_one_is_exactly_choice(self):
        # The contract says these coincide, so neither has to special-case the
        # other. Same element and same consumption, from the same seed.
        one = Mt19937(42)
        one_counter = self.Counter(one)
        picked = one.ChooseWithoutReplacement(Sequence(30), 1)
        one_words = one_counter.Reset()

        other = Mt19937(42)
        other_counter = self.Counter(other)
        chosen = other.Choice(Sequence(30))

        self.assertEqual(picked, [chosen])
        self.assertEqual(one_words, other_counter.Reset())

    def test_choosing_none_consumes_nothing(self):
        rng = Mt19937(42)
        counter = self.Counter(rng)

        self.assertEqual(rng.ChooseWithoutReplacement(Sequence(9), 0), [])
        self.assertEqual(counter.Reset(), 0)

    def test_choosing_more_than_exists_is_an_error(self):
        rng = Mt19937(42)

        with self.assertRaises(ValueError):
            rng.ChooseWithoutReplacement(Sequence(3), 4)
        with self.assertRaises(ValueError):
            rng.ChooseWithoutReplacement(Sequence(3), -1)


class TestTheEngineFacade(RngTestCase):

    def test_choosing_every_element_consumes_no_randomness(self):
        # `docs/rng-contract.md` section 6. Selecting all of them is not a
        # random choice, so it returns input order and does not move the
        # stream. C# has to reproduce this, so it is pinned here too.
        Random.SetSeed(99)
        counter = self.Counter(Random.rand)

        result = Random.RandomChoice2(Sequence(4), 4)

        self.assertEqual(result, [0, 1, 2, 3])
        self.assertEqual(counter.Reset(), 0)

    def test_choosing_some_elements_does_move_the_stream(self):
        Random.SetSeed(99)
        counter = self.Counter(Random.rand)

        Random.RandomChoice2(Sequence(4), 3)

        self.assertGreater(counter.Reset(), 0)

    def test_reseeding_restarts_the_stream(self):
        Random.SetSeed(4242)
        first = [Random.RandomChoice(Sequence(50)) for _ in range(10)]
        Random.SetSeed(4242)
        second = [Random.RandomChoice(Sequence(50)) for _ in range(10)]

        self.assertEqual(first, second)

    def test_the_backend_flag_is_gone(self):
        # `disable_numpy_random` chose between two incompatible generators at
        # runtime. Nothing may reintroduce that.
        import engine.lib.random as module

        self.assertFalse(hasattr(module, "DISABLE_NUMPY_RANDOM"))
        self.assertNotIn("numpy", module.__dict__)


class TestState(RngTestCase):

    def test_a_restored_state_reproduces_the_stream(self):
        rng = Mt19937(42)
        for _ in range(700):  # past the first twist
            rng.NextUInt32()

        state = rng.GetState()
        expected = [rng.NextUInt32() for _ in range(20)]
        rng.SetState(state)

        self.assertEqual([rng.NextUInt32() for _ in range(20)], expected)

    def test_a_snapshot_does_not_move_underneath_the_holder(self):
        rng = Mt19937(42)
        words, index = rng.GetState()

        for _ in range(700):
            rng.NextUInt32()

        self.assertNotEqual((words, index), rng.GetState())
        self.assertEqual(len(words), N)

    def test_a_malformed_state_is_an_error(self):
        rng = Mt19937(42)

        with self.assertRaises(ValueError):
            rng.SetState(([0] * 10, 0))
        with self.assertRaises(ValueError):
            rng.SetState(([0] * N, N + 5))


class TestUndo(RngTestCase):

    def test_undo_rewinds_the_most_recent_draw(self):
        rng = Mt19937(42)
        before = rng.GetState()
        rng.Shuffle(Sequence(10))

        rng.Undo()

        self.assertEqual(rng.GetState(), before)

    def test_undo_past_the_end_is_an_error(self):
        # MARVEL-7 found the old one silently did nothing under one backend.
        rng = Mt19937(42)

        with self.assertRaises(IndexError):
            rng.Undo()

    def test_the_history_is_bounded(self):
        # MARVEL-26: the old implementation appended a full state snapshot per
        # draw to a list only `Undo()` popped.
        rng = Mt19937(42)
        for _ in range(UNDO_DEPTH * 4):
            rng.Choice(Sequence(5))

        self.assertEqual(len(rng.history), UNDO_DEPTH)

    def test_seeding_clears_the_history(self):
        rng = Mt19937(42)
        rng.Choice(Sequence(5))
        rng.Seed(42)

        with self.assertRaises(IndexError):
            rng.Undo()


class TestTheCrossLanguageFixture(RngTestCase):
    """Replay `datasets/rng/vectors.json`, the MARVEL-8 acceptance fixture."""

    @classmethod
    def setUpClass(cls):
        cls.vectors = LoadVectors()

    def test_next_uint32_cases(self):
        for case in self.vectors["cases"]["next_uint32"]:
            with self.subTest(seed=case["seed"], skip=case.get("skip", 0)):
                rng = Mt19937(case["seed"])
                for _ in range(case.get("skip", 0)):
                    rng.NextUInt32()
                actual = [rng.NextUInt32() for _ in range(case["count"])]
                self.assertEqual(actual, case["expect"])

    def test_next_below_cases(self):
        for case in self.vectors["cases"]["next_below"]:
            with self.subTest(seed=case["seed"], n=case["n"]):
                rng = Mt19937(case["seed"])
                counter = self.Counter(rng)
                actual = [rng.NextBelow(case["n"]) for _ in range(case["count"])]
                self.assertEqual(actual, case["expect"])
                self.assertEqual(counter.Reset(), case["words_consumed"])

    def test_shuffle_cases(self):
        for case in self.vectors["cases"]["shuffle"]:
            with self.subTest(seed=case["seed"], length=case["length"]):
                rng = Mt19937(case["seed"])
                counter = self.Counter(rng)
                items = Sequence(case["length"])
                rng.Shuffle(items)
                self.assertEqual(items, case["expect"])
                self.assertEqual(counter.Reset(), case["words_consumed"])

    def test_choice_cases(self):
        for case in self.vectors["cases"]["choice"]:
            with self.subTest(seed=case["seed"], length=case["length"]):
                rng = Mt19937(case["seed"])
                sequence = Sequence(case["length"])
                actual = [rng.Choice(sequence) for _ in range(case["count"])]
                self.assertEqual(actual, case["expect"])

    def test_choose_without_replacement_cases(self):
        for case in self.vectors["cases"]["choose_without_replacement"]:
            with self.subTest(seed=case["seed"], length=case["length"], k=case["k"]):
                rng = Mt19937(case["seed"])
                counter = self.Counter(rng)
                actual = rng.ChooseWithoutReplacement(Sequence(case["length"]), case["k"])
                self.assertEqual(actual, case["expect"])
                self.assertEqual(counter.Reset(), case["words_consumed"])

    def test_engine_choice2_cases(self):
        for case in self.vectors["cases"]["engine_choice2"]:
            with self.subTest(length=case["length"], x=case["x"]):
                Random.SetSeed(case["seed"])
                counter = self.Counter(Random.rand)
                actual = Random.RandomChoice2(Sequence(case["length"]), case["x"])
                self.assertEqual(actual, case["expect"])
                self.assertEqual(counter.Reset(), case["words_consumed"])

    def test_the_mixed_script(self):
        # The case that catches a stream-position error the per-function
        # vectors would each pass through.
        mixed = self.vectors["cases"]["mixed"]
        rng = Mt19937(mixed["seed"])
        counter = self.Counter(rng)

        for index, step in enumerate(mixed["steps"]):
            with self.subTest(step=index, op=step["op"]):
                op = step["op"]
                if op == "next_uint32":
                    actual = rng.NextUInt32()
                elif op == "next_below":
                    actual = rng.NextBelow(step["n"])
                elif op == "choice":
                    actual = rng.Choice(Sequence(step["length"]))
                elif op == "choose_without_replacement":
                    actual = rng.ChooseWithoutReplacement(
                        Sequence(step["length"]), step["k"])
                elif op == "shuffle":
                    actual = Sequence(step["length"])
                    rng.Shuffle(actual)
                else:
                    self.fail(f"unknown op in the fixture: {op}")

                self.assertEqual(actual, step["result"])
                self.assertEqual(counter.Reset(), step["words_consumed"])

    def test_the_fixture_is_not_stale(self):
        # Guards the failure mode where the generator changes and the fixture
        # does not, leaving MARVEL-8 accepted against the old contract.
        from tools.rng.emit_vectors import Build, Serialise

        with open(VECTORS, "r", encoding="utf-8") as handle:
            on_disk = handle.read()

        self.assertEqual(
            on_disk, Serialise(Build()),
            "datasets/rng/vectors.json is stale; run: python -m tools.rng.emit_vectors")


if __name__ == "__main__":
    unittest.main()


