<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Marvel.View</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Marvel.Rules/Marvel.Rules.csproj" />
  </ItemGroup>

</Project>
