using Marvel.Cards.Dsl;
using Marvel.Content.Setup;
using Marvel.Content.Tests.Cards;
using Marvel.Rules.Events;
using Marvel.Rules.Play;
using Marvel.Rules.Prompts;
using Marvel.Rules.State;
using Marvel.Rules.Timing;
using Marvel.Tests;
using Xunit;

namespace Marvel.Content.Tests.Play;
public sealed class ActionAbilityPaymentsAndAuthorizationAPrintedTextBoxResourceAbilityPaysAPrintedResourceCostTests
{
    [Rule("rr:printed.1")]
    [Rule("rr:text-box.1.1")]
    [Fact]
    public void APrintedTextBoxResourceAbilityPaysAPrintedResourceCost()
    {
        // “They may use resources generated by a card's ability, so long as
        // the icon for the resource that card generates is printed in its text
        // box.” Peter Parker's Scientist icon is marked from printed card data
        // and appears beside printed hand icons in this narrower generator menu.
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """{ "spendPrinted": "B" }""", includeAuthored: true);
        Card? source = null;
        var(game, world) = Playing(board =>
        {
            Hand(board, Physicals, 0);
            source = InPlay(board, AuthoredCards.AuntMay);
        }, abilities: runner);
        int peter = world.Seats[0].IdentityCard.ObjectId;
        var action = Assert.Single(game.Pending!.Affordances, option => option.AnchorId == source!.ObjectId && option.CostOptions.Any(cost => cost.ResourceCosts.Any(component => component.Printed)));
        var price = Assert.Single(action.CostOptions);
        Assert.Contains(price.Generators, generator => generator.Effect == peter);
        Assert.True(Assert.Single(price.ResourceCosts).Printed);
        game.Resolve(Decision.Take(action.Id, [], [peter]));
        Assert.DoesNotContain(runner.ResourceAbilities(world, 0), generator => generator.Effect == peter);
    }

    [Rule("rr:printed.1.1")]
    [Fact]
    public void APrintedWildCannotSubstituteForAPrintedPhysicalCost()
    {
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """{ "spendPrinted": "R" }""", includeAuthored: true);
        Card? source = null;
        Card? wild = null;
        var(_, world) = Playing(board =>
        {
            Hand(board, Physicals, 0);
            source = InPlay(board, AuthoredCards.AuntMay);
            wild = board.CreateCard("01011", board.Seats[0].Hand);
        }, abilities: runner);
        foreach (var other in world.Seats[0].Hand.Cards.Where(card => card != wild).ToList())
        {
            World.MoveToTop(other, world.Seats[0].Deck);
        }

        Assert.DoesNotContain(runner.Actions(world, 0), ability => ability.Card == source!.ObjectId && ability.Ordinal == 1);
        Assert.Same(world.Seats[0].Hand, wild!.Area);
    }

    [Rule("rr:cost.5")]
    [Rule("rr:printed.1")]
    [Fact]
    public void SimultaneousPrintedResourceCostsShareOneExactPayment()
    {
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """{ "seq": [ { "spendPrinted": "B" }, { "spendPrinted": "Y" } ] }""", includeAuthored: true);
        Card? source = null;
        Card? energy = null;
        var(_, world) = Playing(board =>
        {
            source = InPlay(board, AuthoredCards.AuntMay);
            energy = board.CreateCard("01093", board.Seats[0].Hand);
        }, abilities: runner);
        foreach (var other in world.Seats[0].Hand.Cards.Where(card => card != energy).ToList())
        {
            World.MoveToTop(other, world.Seats[0].Deck);
        }

        int peter = world.Seats[0].IdentityCard.ObjectId;
        var ability = Assert.Single(runner.Actions(world, 0), pending => pending.Card == source!.ObjectId && pending.Ordinal == 1);
        var price = Assert.Single(runner.Describe(world, ability).CostOptions);
        Assert.Equal(2, price.ResourceCosts.Count);
        Assert.All(price.ResourceCosts, component => Assert.True(component.Printed));
        runner.Act(world, ability, [peter, energy!.ObjectId], []);
        Assert.Equal(DeckType.DiscardPile, energy.Area.Type);
        Assert.DoesNotContain(runner.ResourceAbilities(world, 0), generator => generator.Effect == peter);
    }

    [Rule("rr:cost.7")]
    [Rule("rr:cost.8")]
    [Fact]
    public void AnOutOfPlayCostCanUseOnlyThePayingPlayersArea()
    {
        // A hand is out of play, and a payer "may only use game elements that
        // are in their own out-of-play areas." The prompt therefore offers
        // only the payer's hand, and forging another player's card is rejected
        // before either card moves.
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """{ "discardFromHand": 1 }""");
        Card? source = null;
        Card? otherPlayersCard = null;
        var(_, world) = Playing(board =>
        {
            source = InPlay(board, AuthoredCards.AuntMay);
            otherPlayersCard = board.CreateCard(Physicals, board.Seats[1].Hand);
        }, heroes: ["spider_man", "captain_marvel"], abilities: runner);
        var ability = Assert.Single(runner.Actions(world, 0), pending => pending.Card == source!.ObjectId);
        var targets = Assert.IsType<TargetRequest>(runner.Describe(world, ability).Targets);
        Assert.DoesNotContain(otherPlayersCard!.ObjectId, targets.Legal);
        Assert.Throws<RulesNotImplementedException>(() => runner.Act(world, ability, [], [otherPlayersCard.ObjectId]));
        Assert.Same(world.Seats[1].Hand, otherPlayersCard.Area);
        Assert.Equal(DeckType.SupportsArea, source!.Area.Type);
    }

    [Rule("rr:cost.7.1")]
    [Rule("rr:cost.7.2")]
    [Fact]
    public void AChosenFriendlyCostCanUseAnotherPlayersCard()
    {
        // A cost that "uses the word 'choose'" or targets a "friendly" card
        // may choose cards the payer does not control.
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """
            { "exhaustChosen": {
              "from": { "query": "heroesAndAllies" },
              "count": 1
            } }
            """);
        Card? source = null;
        Card? friendly = null;
        var(_, world) = Playing(board =>
        {
            source = InPlay(board, AuthoredCards.AuntMay);
            friendly = board.CreateCard(AuthoredCards.BlackCat, board.AreaOf(DeckType.AlliesArea, PlayArea.Of(1), cardOwner: 1));
        }, heroes: ["spider_man", "captain_marvel"], abilities: runner);
        var ability = Assert.Single(runner.Actions(world, 0), pending => pending.Card == source!.ObjectId);
        var targets = Assert.IsType<TargetRequest>(runner.Describe(world, ability).Targets);
        Assert.Contains(friendly!.ObjectId, targets.Legal);
        Assert.DoesNotContain(world.Seats[1].IdentityCard.ObjectId, targets.Legal);
        runner.Act(world, ability, [], [friendly.ObjectId]);
        Assert.False(friendly.Ready);
    }

    [Rule("rr:cost.9")]
    [Theory]
    [InlineData("{ \"discardUpToFromHand\": 3 }")]
    [InlineData("{ \"discardAnyFromHand\": \"yourHand\" }")]
    public void UpToAndAnyNumberCostsRequireAtLeastOne(string cost)
    {
        // A cost requiring "any number" or "up to" a number "requires a
        // minimum of one such game element."
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: cost);
        Card? source = null;
        var(_, world) = Playing(board => source = InPlay(board, AuthoredCards.AuntMay), abilities: runner);
        var ability = Assert.Single(runner.Actions(world, 0), pending => pending.Card == source!.ObjectId);
        var targets = Assert.IsType<TargetRequest>(runner.Describe(world, ability).Targets);
        int held = world.Seats[0].Hand.Cards.Count;
        Assert.Equal(1, targets.Min);
        Assert.True(targets.Max >= 1);
        Assert.Throws<RulesNotImplementedException>(() => runner.Act(world, ability, [], []));
        Assert.Equal(held, world.Seats[0].Hand.Cards.Count);
        int paid = targets.Legal[0];
        runner.Act(world, ability, [], [paid]);
        Assert.Equal(DeckType.DiscardPile, world.Cards[paid].Area.Type);
    }

    [Rule("rr:cost.5")]
    [Rule("rr:cost.10")]
    [Fact]
    public void AnUnpayableSimultaneousCostChangesNoState()
    {
        // The resource half is invalid, so the exhaust half is not paid first.
        // The forged action is rejected with the source still ready.
        var runner = Runner(AuthoredCards.AuntMay, "Action", """{ "draw": { "player": "you", "count": 1 } }""", cost: """{ "seq": [ { "exhaust": "this" }, { "spend": "B" } ] }""");
        Card? source = null;
        var(_, world) = Playing(board =>
        {
            source = InPlay(board, AuthoredCards.AuntMay);
            Hand(board, Physicals, 1);
        }, abilities: runner);
        var forged = new PendingAbility(source!.ObjectId, AbilityType.Action, 0);
        Assert.Throws<RulesNotImplementedException>(() => runner.Act(world, forged, [world.Seats[0].Hand.Cards[0].ObjectId], []));
        Assert.True(source!.Ready);
    }

    [Rule("rr:player-turn.5")]
    [Rule("rr:player-turn.6")]
    [Fact]
    public void ASharedEncounterActionIsOfferedForEveryEligiblePlayer()
    {
        // The request is implied, but the acting seat is material: that player
        // supplies the resources and resolves every reference to "you".
        Card? horn = null;
        var(game, _) = Playing(board =>
        {
            board.Seats[0].IdentityCard.TurnTo(AuthoredCards.SpiderMan);
            board.Seats[1].IdentityCard.TurnTo("01010a");
            horn = board.CreateCard(AuthoredCards.IvoryHorn, board.AreaOf(DeckType.RevealingArea));
            board.Abilities = AuthoredCards.Runner();
            Reveal.Resolve(board, CardCatalogData, horn, 0, []);
            foreach (var card in board.Seats[0].Hand.Cards.ToList())
            {
                World.MoveToTop(card, board.Seats[0].Deck);
            }

            Hand(board, player: 1, Physicals, count: 3);
        }, heroes: ["spider_man", "captain_marvel"]);
        var actions = game.Pending!.Affordances.Where(option => option.Verb == Game.ActionVerb && option.AnchorId == horn!.ObjectId).ToList();
        Assert.Equal([0, 1], actions.Select(action => action.AnchorPlayer));
        Assert.Equal(2, actions.Select(action => action.Id).Distinct().Count());
    }

    [Rule("rr:ability.8.2")]
    [Rule("rr:action.1.1")]
    [Rule("rr:obligation.6")]
    [Fact]
    public void OnlyThePlayerHoldingAnObligationMayTriggerItsAction()
    {
        // "Only the player with the obligation in their play area can trigger
        // abilities or pay costs on that obligation." It remains an encounter
        // card, but this is the exception to the general permission to use
        // encounter-card actions.
        // The second player's turn can request another player's ordinary
        // action; it cannot request the obligation sitting in player zero's
        // play area.
        var runner = Runner(AuthoredCards.EvictionNotice, "Action", """{ "draw": { "player": "you", "count": 1 } }""");
        Card? obligation = null;
        var(_, world) = Playing(board => obligation = board.CreateCard(AuthoredCards.EvictionNotice, board.AreaOf(DeckType.ObligationsArea, PlayArea.Of(0))), heroes: ["spider_man", "captain_marvel"], abilities: runner);
        Assert.Contains(runner.Actions(world, 0), action => action.Card == obligation!.ObjectId);
        Assert.DoesNotContain(runner.Actions(world, 1), action => action.Card == obligation!.ObjectId);
    }
}
