using Marvel.Rules.Play;
using Marvel.Rules.Prompts;
using Marvel.Tests;
using Xunit;

namespace Marvel.Rules.Tests.Prompts;

public sealed class ResourcePaymentTests
{
    [Rule("rr:cost.5")]
    [Rule("rr:cost.5.1")]
    [Fact]
    public void ADoubleResourceCanBeDividedBetweenSimultaneousCosts()
    {
        // “If a single game element has multiple costs that must be paid
        // simultaneously, the player chooses how to divide the resource
        // generated by the ability between those costs.”
        var cost = new CostOption(
            0,
            "2",
            Sources: [new ResourceSource(17, "YY")],
            Components: [new ResourceCost("1", ["Y"]), new ResourceCost("1")]);

        var allocation = ResourcePayment.Allocate(cost, [17]);

        Assert.Equal(
            [
                new ResourceAllocation(17, 0, "Y"),
                new ResourceAllocation(17, 1, "Y"),
            ],
            allocation);
    }

    [Rule("rr:cost.4.1")]
    [Rule("rr:wild-resource")]
    [Fact]
    public void ExactTypesAreUsedBeforeWildsAndExcessIsNotAllocated()
    {
        // Generated resources beyond the cost are not paid. A wild may be
        // declared as any type, but the deterministic research-policy choice
        // preserves it when an exact icon meets the requirement.
        var cost = new CostOption(
            0,
            "2",
            Rule: ["R"],
            Sources:
            [
                new ResourceSource(10, "GY"),
                new ResourceSource(11, "R"),
            ]);

        var allocation = ResourcePayment.Allocate(cost, [10, 11]);

        Assert.Equal(
            [
                new ResourceAllocation(11, 0, "R"),
                new ResourceAllocation(10, 0, "G"),
            ],
            allocation);
        Assert.Equal(2, allocation!.Sum(part => part.PaidAs.Length));
    }

    [Rule("rr:non-numerical-variable.1")]
    [Fact]
    public void AnExplicitVariableValueSetsTheNumberOfAllocatedIcons()
    {
        var cost = new CostOption(
            0,
            "X",
            Sources: [new ResourceSource(4, "BBB")],
            Variables: [new VariableRequest("X", 0, 3)]);

        var allocation = ResourcePayment.Allocate(
            cost,
            [4],
            new Dictionary<string, long>(StringComparer.Ordinal) { ["X"] = 2 });

        Assert.Equal([new ResourceAllocation(4, 0, "BB")], allocation);
    }

    [Fact]
    public void APaymentThatCannotMeetAComponentHasNoAllocation()
    {
        var cost = new CostOption(
            0,
            "1",
            Sources: [new ResourceSource(2, "B")],
            Components: [new ResourceCost("1", ["Y"])]);

        Assert.Null(ResourcePayment.Allocate(cost, [2]));
    }

    [Rule("rr:printed.1.1")]
    [Fact]
    public void APrintedCostDoesNotDeclareAWildAsAnotherType()
    {
        // “Wild resources cannot be spent as other resource types for such a
        // cost.” The same icon remains legal for an ordinary physical cost.
        var printed = new CostOption(
            0,
            "1",
            Rule: ["R"],
            Sources: [new ResourceSource(7, "G")],
            Components: [new ResourceCost("1", ["R"], Printed: true)]);

        Assert.Null(ResourcePayment.Allocate(printed, [7]));
        Assert.True(Resources.Pays("G", 1, "R"));
        Assert.False(Resources.PaysPrinted("G", 1, "R"));
        Assert.True(Resources.PaysPrinted("G", 1, "G"));
    }
}
