<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <MarvelPresentationRole>Godot</MarvelPresentationRole>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Marvel.Core/Marvel.Core.csproj" />
  </ItemGroup>

</Project>
