<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Marvel.Release</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Marvel.Server/Marvel.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Marvel.Release.Tests" />
  </ItemGroup>

</Project>
