extends "res://smoke/local_game_smoke_card_summary.gd"


func _close_inspector_with_keyboard(hand_card: Control, inspector: Control) -> bool:
	var escape := InputEventKey.new()
	escape.keycode = KEY_ESCAPE
	escape.pressed = true
	render_viewport.push_input(escape)
	var release := InputEventKey.new()
	release.keycode = KEY_ESCAPE
	render_viewport.push_input(release)
	await process_frame
	if inspector.visible:
		_fail("Escape did not close the card inspector")
		return false
	if render_viewport.gui_get_focus_owner() != hand_card:
		_fail("closing the card inspector did not restore card focus")
		return false
	return true


func _capture_named_card(title: String, checkpoint: String) -> bool:
	var card: Control = null
	for candidate in main.find_children("*", "", true, false):
		var face := candidate.find_child("CardFace", false, false)
		if face == null:
			continue
		var title_label := face.find_child("Title", false, false) as Label
		if title_label != null and title_label.text == title:
			card = candidate as Control
			break
	if card == null:
		_fail("the table has no readable '%s' card for visual inspection" % title)
		return false
	if not await _pointer_activate_card_body(card):
		return false
	await process_frame
	var inspector := main.get_node("CardInspector") as Control
	if not inspector.visible:
		_fail("'%s' did not open for visual inspection" % title)
		return false
	if not await _capture_checkpoint(checkpoint):
		return false
	return await _close_inspector_with_keyboard(card, inspector)


func _prepare_art_pack() -> void:
	var root_path := ProjectSettings.globalize_path("user://smoke-art-pack")
	DirAccess.make_dir_recursive_absolute(root_path)
	var illustration := Image.create(4, 4, false, Image.FORMAT_RGBA8)
	illustration.fill(Color(0.2, 0.55, 0.75, 1.0))
	illustration.save_png(root_path.path_join("peter-parker.png"))
	var invalid := FileAccess.open(root_path.path_join("rhino.png"), FileAccess.WRITE)
	invalid.store_string("not an image")
	invalid.close()
	var manifest := FileAccess.open(root_path.path_join("manifest.json"), FileAccess.WRITE)
	manifest.store_string(JSON.stringify({
		"version": 1,
		"entries": {
			"01001b": {
				"file": "peter-parker.png",
				"authorized": true,
				"rights": "Generated by the native smoke test for local verification."
			},
			"01094": {
				"file": "rhino.png",
				"authorized": true,
				"rights": "Invalid fixture generated by the native smoke test."
			}
		}
	}))
	manifest.close()
	OS.set_environment("MARVEL_ART_PACK", root_path)


func _web_shooter_draft_is_prepared() -> bool:
	var modal := main.find_child("PaymentModal", true, false) as Control
	if modal != null and modal.is_visible_in_tree(): return true
	return _table_card_control("Card*Target") != null \
		or _table_card_control("Card*Generator") != null \
		or _table_card_control("Card*Cost") != null \
		or _table_card_control("Card*Submit") != null


func _table_card_control(name: String) -> Button:
	for candidate in main.find_children(name, "Button", true, false):
		var button := candidate as Button
		if button != null and not button.is_queued_for_deletion() \
				and button.is_visible_in_tree() \
				and ((button.get_parent() != null and button.get_parent().name == "DirectControls") \
					or button.has_meta("spatial_card_anchor")):
			return button
	return null


func _wait_for_web_shooter_draft(failure: String) -> bool:
	if await _wait_for(func() -> bool: return _web_shooter_draft_is_prepared()):
		return true
	_fail("%s; table=%s" % [failure, _visible_text(_play())])
	return false
