using Marvel.Rules.State;
using Marvel.Rules.Timing;

namespace Marvel.Rules.Play;

internal sealed record AgendaOperationData(
    int Subject = -1,
    int Seat = -1,
    bool Plan = false,
    int Character = -1,
    AbilityType? Tier = null,
    ThreatPlacement? Placement = null,
    int ActivationId = -1,
    bool FinalStep = false,
    bool FinalPlayer = false,
    bool EachPlayerFrame = false,
    string Trigger = "",
    CharacterAttack? CharacterAttack = null,
    CharacterThwart? CharacterThwart = null,
    PlayerAction? PlayerAction = null,
    bool SurgeGained = false,
    IReadOnlyList<int>? Discarded = null,
    IReadOnlyList<int>? ActivatedEnemies = null,
    IReadOnlyList<int>? ActivationPlayers = null,
    int AbilityOrdinal = -1,
    IReadOnlyList<int>? ProcedureCandidates = null,
    IReadOnlyList<int>? ActivationOrder = null,
    IReadOnlyList<PendingAbility>? ProcedureAbilities = null,
    IReadOnlyList<int>? ProcedurePlayersPassed = null,
    Occurrence? ProcedureOccurrence = null,
    int ProcedureSource = -1,
    Occurrence? ProcedureOwnerOccurrence = null,
    string ProcedureTrigger = "",
    string ProcedureVerb = "",
    int ProcedureBy = -1,
    long ProcedureAmount = 0,
    IReadOnlyDictionary<int, long>? ProcedureAmounts = null,
    bool ProcedureFlag = false,
    IReadOnlyList<string>? AbilityPath = null,
    IReadOnlyList<int>? AbilityActivationIds = null,
    IReadOnlyDictionary<string, long>? AbilityResults = null,
    Occurrence? AbilityOccurrence = null,
    string AbilityFace = "",
    int AbilityPlayer = -1,
    int AbilityActor = -1,
    bool AbilityHasContinuation = false);
