using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;
using Marvel.Cards.Dsl;
using Marvel.Cards.Run;
using Marvel.Content;
using Marvel.Content.Behavior;
using Marvel.Content.Setup;
using Marvel.Rules.Events;
using Marvel.Rules.Play;
using Marvel.Rules.Prompts;
using Marvel.Rules.State;
using Marvel.Rules.Timing;

namespace Marvel.Behavior.Run;

internal static class ThenTranscriptVocabulary
{
    internal static IReadOnlyList<TranscriptBinding> Bindings() =>
    [
        Bind("pending-opportunity-offered", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is offered the ""(?<label>[^""]+)"" pending opportunity",
            PendingOpportunityOffered),
        Bind("pending-window-pass", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) may pass the pending window",
            PendingWindowPass),
        Bind("pending-option-availability", TranscriptStepKind.Then,
            @"option (?<option>\d+) is (?<availability>offered|not offered) by the pending decision",
            PendingOptionAvailability),
        Bind("hand-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has (?<count>\d+) cards? in hand", HandCount),
        Bind("mulligan-offered", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is offered a mulligan", MulliganOffered),
        Bind("active-player", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is the active player", ActivePlayer),
        Bind("end-phase-discard-offered", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is offered the end-of-player-phase discard",
            EndPhaseDiscardOffered),
        Bind("pending-setup-card-offered", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is offered by the pending setup ability",
            PendingCardOffered),
        Bind("pending-setup-card-not-offered", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is not offered by the pending setup ability",
            PendingCardNotOffered),
        Bind("pending-order-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is asked to order (?<count>\d+) cards? for the pending action",
            PendingOrderCount),
        Bind("simultaneous-effect-choice-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is asked to choose between (?<count>\d+) simultaneous effects",
            SimultaneousEffectChoiceCount),
        Bind("pending-choice-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is asked to choose (?<count>\d+) cards? for the pending action",
            PendingChoiceCount),
        Bind("pending-choice-range", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is asked to choose between (?<min>\d+) and (?<max>\d+) cards? for the pending action",
            PendingChoiceRange),
        Bind("pending-player-order-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is asked to order (?<count>\d+) players? for the pending encounter-card decision",
            PendingPlayerOrderCount),
        Bind("setup-deck-shuffled", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s player deck was shuffled by the setup ability",
            SetupDeckShuffled),
        Bind("card-player-hand", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in seat (?<seat>\d+)'s hand",
            CardInPlayerHand),
        Bind("card-player-deck", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in seat (?<seat>\d+)'s player deck",
            CardInPlayerDeck),
        Bind("player-deck-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has (?<count>\d+) cards? in their player deck", PlayerDeckCount),
        Bind("player-deck-top-face", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s player deck has card (?<face>\d+[a-z]?) on top",
            PlayerDeckTopFace),
        Bind("player-discard-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has (?<count>\d+) cards? in their discard pile", PlayerDiscardCount),
        Bind("encounter-queue-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has (?<count>\d+) facedown encounter cards?", EncounterCount),
        Bind("facedown-encounter-queue-card", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is facedown in seat (?<seat>\d+)'s encounter queue",
            FacedownEncounterQueueCard),
        Bind("encounter-deck-count", TranscriptStepKind.Then,
            @"the encounter deck has (?<count>\d+) cards?", EncounterDeckCount),
        Bind("encounter-deck-face-counts", TranscriptStepKind.Then,
            "the encounter deck contains these card counts", EncounterDeckFaceCounts),
        Bind("owned-player-card-counts", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s player cards contain these counts",
            OwnedPlayerCardCounts),
        Bind("setup-authority", TranscriptStepKind.Then,
            @"the dealt scene matches setup authority ""(?<authority>setup:(?:campaign|hero|encounter-set):[a-z0-9_]+)""",
            SetupAuthority),
        Bind("player-count", TranscriptStepKind.Then,
            @"the game has (?<count>\d+) players?", PlayerCount),
        Bind("encounter-discard-count", TranscriptStepKind.Then,
            @"the encounter discard pile has (?<count>\d+) cards?", EncounterDiscardCount),
        Bind("acceleration-token-count", TranscriptStepKind.Then,
            @"the main scheme has (?<count>\d+) acceleration tokens?", AccelerationTokenCount),
        Bind("card-readiness", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is (?<state>ready|exhausted)",
            CardReadiness),
        Bind("generated-resources", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) generated (?<resources>[A-Z]+) resources",
            GeneratedResources),
        Bind("last-attack-defense", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) defended the last attack without a basic defense",
            LastAttackDefense),
        Bind("last-attack-undefended", TranscriptStepKind.Then,
            "the last attack was undefended", LastAttackUndefended),
        Bind("card-player-discard", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in seat (?<seat>\d+)'s discard pile",
            CardInPlayerDiscard),
        Bind("card-top-player-discard", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is faceup on top of seat (?<seat>\d+)'s discard pile",
            CardOnTopOfPlayerDiscard),
        Bind("card-top-encounter-discard", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is faceup on top of the encounter discard pile",
            CardOnTopOfEncounterDiscard),
        Bind("card-encounter-discard", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in the encounter discard pile",
            CardInEncounterDiscard),
        Bind("card-resolving", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is faceup in the resolving area",
            CardResolving),
        Bind("player-discard-order", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s discard pile has these cards from top to bottom",
            PlayerDiscardOrder),
        Bind("event-card-order", TranscriptStepKind.Then,
            @"the (?<verb>[A-Za-z_]+) events moved these cards in order",
            EventCardOrder),
        Bind("not-eliminated", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is not eliminated", NotEliminated),
        Bind("game-unfinished", TranscriptStepKind.Then,
            "the game is unfinished", GameUnfinished),
        Bind("event-emitted", TranscriptStepKind.Then,
            @"a (?<verb>[A-Za-z_]+) event with trigger (?<trigger>.+) was emitted", EventEmitted),
        Bind("event-count", TranscriptStepKind.Then,
            @"(?<count>\d+) (?<verb>[A-Za-z_]+) events? (?:was|were) emitted", EventCount),
        Bind("boost-card-flip-count", TranscriptStepKind.Then,
            @"(?<count>\d+) cards? (?:was|were) turned faceup as boost cards?",
            BoostCardFlipCount),
        Bind("event-order", TranscriptStepKind.Then,
            @"(?:a|an) (?<first>[A-Za-z_]+) event was emitted before (?:a|an) (?<second>[A-Za-z_]+) event",
            EventOrder),
        Bind("players-lose", TranscriptStepKind.Then,
            "the players lose the game", PlayersLose),
        Bind("villain-wins", TranscriptStepKind.Then,
            "the villain wins the game", VillainWins),
        Bind("players-win", TranscriptStepKind.Then,
            "the players win the game", PlayersWin),
        Bind("seat-eliminated", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is eliminated", SeatEliminated),
        Bind("attack-ended", TranscriptStepKind.Then,
            "the attack has ended", AttackEnded),
        Bind("player-play-area-removed", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s play area is removed", PlayerPlayAreaRemoved),
        Bind("first-player", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has the first player token", FirstPlayer),
        Bind("minion-engaged", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is engaged with seat (?<seat>\d+)",
            MinionEngaged),
        Bind("facedown-drone-count", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) has (?<count>\d+) facedown Drone minions?",
            FacedownDroneCount),
        Bind("ally-controlled", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) remains an ally controlled by seat (?<seat>\d+)",
            AllyControlled),
        Bind("support-controlled", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) remains a support controlled by seat (?<seat>\d+)",
            SupportControlled),
        Bind("card-owned", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is owned by seat (?<seat>\d+)",
            CardOwned),
        Bind("card-controlled", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is controlled by seat (?<seat>\d+)",
            CardControlled),
        Bind("card-damage", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has (?<count>\d+) damage",
            CardDamage),
        Bind("card-remaining-hit-points", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has (?<count>\d+) remaining hit points",
            CardRemainingHitPoints),
        Bind("card-counters", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has (?<count>\d+) (?<type>[a-z-]+) counters?",
            CardCounters),
        Bind("card-target-availability", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is (?<availability>available|unavailable) as a target",
            CardTargetAvailability),
        Bind("basic-recovery-result", TranscriptStepKind.Then,
            @"basic recovery is (?<availability>available|unavailable)",
            BasicRecoveryResult),
        Bind("voluntary-form-change-result", TranscriptStepKind.Then,
            @"a voluntary form change is (?<availability>available|unavailable)",
            BasicRecoveryResult),
        Bind("card-play-result", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is (?<availability>available|unavailable) to play",
            CardPlayResult),
        Bind("modified-card-cost", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has modified resource cost (?<count>\d+) for seat (?<seat>\d+)",
            ModifiedCardCost),
        Bind("modified-card-statistic", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has modified (?<field>ATK|DEF|HS|REC|THW) (?<count>\d+)",
            ModifiedCardStatistic),
        Bind("card-removed", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is removed from the game",
            CardRemoved),
        Bind("card-is-villain", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is the faceup villain",
            CardIsVillain),
        Bind("card-in-villain-deck", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in the villain deck",
            CardInVillainDeck),
        Bind("card-is-main-scheme", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is the faceup main scheme",
            CardIsMainScheme),
        Bind("card-in-encounter-deck", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in the encounter deck",
            CardInEncounterDeck),
        Bind("card-in-seat-nemesis", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in seat (?<seat>\d+)'s set-aside nemesis pile",
            CardInSeatNemesis),
        Bind("card-in-play", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in play", CardInPlay),
        Bind("card-out-of-play", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is out of play", CardOutOfPlay),
        Bind("card-player-play-area", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in seat (?<seat>\d+)'s play area",
            CardInPlayerPlayArea),
        Bind("card-not-player-play-area", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is not in seat (?<seat>\d+)'s play area",
            CardNotInPlayerPlayArea),
        Bind("card-villain-play-area", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is in the villain's play area",
            CardInVillainPlayArea),
        Bind("card-not-villain-play-area", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is not in the villain's play area",
            CardNotInVillainPlayArea),
        Bind("player-order", TranscriptStepKind.Then,
            @"the player order is (?<order>[\d,]+)", PlayerOrder),
        Bind("per-player-count", TranscriptStepKind.Then,
            @"the per-player count is (?<count>\d+)", PerPlayerCount),
        Bind("card-event-order", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) had a (?<first>[A-Za-z_]+) event before an (?<second>[A-Za-z_]+) event",
            CardEventOrder),
        Bind("card-discard-after-event", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) was discarded after a (?<verb>[A-Za-z_]+) event",
            CardDiscardAfterEvent),
        Bind("seat-form", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) is in (?<form>hero|alter-ego) form", SeatForm),
        Bind("identity-face-out-of-play", TranscriptStepKind.Then,
            @"seat (?<seat>\d+)'s identity face (?<face>\d+[a-z]?) is out of play",
            IdentityFaceOutOfPlay),
        Bind("form-transition", TranscriptStepKind.Then,
            @"seat (?<seat>\d+) changed from (?<from>hero|alter-ego) to (?<to>hero|alter-ego) form",
            FormTransition),
        Bind("card-status", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has a (?<status>stunned|confused|tough) status card",
            CardStatus),
        Bind("upgrade-attached-identity", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) remains attached to seat (?<seat>\d+)'s identity",
            UpgradeAttachedIdentity),
        Bind("card-attached-card", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is attached to card (?<host>\d+[a-z]?) copy (?<hostCopy>\d+)",
            CardAttachedToCard),
        Bind("facedown-card-attached-card", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is facedown attached to card (?<host>\d+[a-z]?) copy (?<hostCopy>\d+)",
            FacedownCardAttachedToCard),
        Bind("status-count", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has (?<count>\d+) (?<status>stunned|confused|tough) status cards?",
            StatusCount),
        Bind("card-afflicted", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is (?<status>stunned|confused)",
            CardAfflicted),
        Bind("card-trait", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) has the (?<trait>[A-Z][A-Z ]*) trait",
            CardTrait),
        Bind("card-no-trait", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) does not have the (?<trait>[A-Z][A-Z ]*) trait",
            CardDoesNotHaveTrait),
        Bind("printed-characteristics", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) exposes these printed characteristics",
            PrintedCharacteristics),
        Bind("pending-card-offered", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is offered by the pending action",
            PendingCardOffered),
        Bind("pending-card-not-offered", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is not offered by the pending action",
            PendingCardNotOffered),
        Bind("no-pending-opportunity", TranscriptStepKind.Then,
            "no opportunity is pending", NoPendingOpportunity),
        Bind("combined-triggering-conditions", TranscriptStepKind.Then,
            @"the pending occurrence combines (?<first>[A-Za-z_]+) and (?<second>[A-Za-z_]+)",
            CombinedTriggeringConditions),
        Bind("card-action-availability", TranscriptStepKind.Then,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s action is (?<availability>available|unavailable)",
            CardActionAvailability),
        Bind("cataloged-exception", TranscriptStepKind.Then,
            "the engine raises the cataloged unimplemented rule exception", CatalogedException),
    ];
}
