using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;
using Marvel.Cards.Dsl;
using Marvel.Cards.Run;
using Marvel.Content;
using Marvel.Content.Behavior;
using Marvel.Content.Setup;
using Marvel.Rules.Events;
using Marvel.Rules.Play;
using Marvel.Rules.Prompts;
using Marvel.Rules.State;
using Marvel.Rules.Timing;

namespace Marvel.Behavior.Run;

internal static class WhenTranscriptVocabulary
{
    internal static IReadOnlyList<TranscriptBinding> Bindings() =>
    [
        Bind("draw-cards", TranscriptStepKind.When,
            @"seat (?<seat>\d+) draws (?<count>\d+) cards?", DrawCards),
        Bind("discard-player-deck", TranscriptStepKind.When,
            @"seat (?<seat>\d+) discards the top (?<count>\d+) cards? of their player deck",
            DiscardPlayerDeck),
        Bind("discard-from-hand", TranscriptStepKind.When,
            @"seat (?<seat>\d+) discards card (?<face>\d+[a-z]?) copy (?<copy>\d+) from hand",
            DiscardFromHand),
        Bind("discard-card-effect", TranscriptStepKind.When,
            @"an effect attempts to discard card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            DiscardCardEffect),
        Bind("deal-encounter-cards", TranscriptStepKind.When,
            @"seat (?<seat>\d+) is dealt (?<count>\d+) encounter cards?",
            DealEncounterCards),
        Bind("discard-encounter-deck", TranscriptStepKind.When,
            @"the top (?<count>\d+) cards? of the encounter deck (?:is|are) discarded",
            DiscardEncounterDeck),
        Bind("reveal-encounter-card", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is revealed to seat (?<seat>\d+)",
            RevealEncounterCard),
        Bind("reveal-encounter-card-with-defender", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is revealed to seat (?<seat>\d+) with card (?<defender>\d+[a-z]?) copy (?<defenderCopy>\d+) defending its attack",
            RevealEncounterCardWithDefender),
        Bind("reveal-encounter-card-with-defender-opportunity", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) is revealed to seat (?<seat>\d+) accepting ""(?<label>[^""]+)"" with card (?<defender>\d+[a-z]?) copy (?<defenderCopy>\d+) defending its attack",
            RevealEncounterCardWithDefenderAndOpportunity),
        Bind("assign-threat-accepting", TranscriptStepKind.When,
            @"(?<count>\d+) threat is assigned to the main scheme for seat (?<seat>\d+) accepting ""(?<label>[^""]+)""",
            AssignThreatAccepting),
        Bind("begin-threat-assignment", TranscriptStepKind.When,
            @"(?<count>\d+) threat begins assignment to the main scheme for seat (?<seat>\d+)",
            BeginThreatAssignment),
        Bind("answer-encounter-card", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses option (?<option>\d+) for the pending encounter-card decision",
            AnswerEncounterCard),
        Bind("answer-encounter-card-with-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses option (?<option>\d+) paying with these cards for the pending encounter-card decision",
            AnswerEncounterCardWithPayment),
        Bind("order-pending-players", TranscriptStepKind.When,
            @"seat (?<seat>\d+) orders these players for the pending encounter-card decision",
            OrderPendingPlayers),
        Bind("phase-discard-none", TranscriptStepKind.When,
            @"seat (?<seat>\d+) keeps every card during the optional end-of-player-phase discard",
            PhaseDiscardNone),
        Bind("phase-discard-selected", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses these cards for the end-of-player-phase discard",
            PhaseDiscardSelected),
        Bind("phase-draw", TranscriptStepKind.When,
            "the end-of-player-phase draw step resolves", PhaseDraw),
        Bind("phase-ready", TranscriptStepKind.When,
            "the end-of-player-phase ready step resolves", PhaseReady),
        Bind("end-player-phase", TranscriptStepKind.When,
            "the player phase ends", EndPlayerPhase),
        Bind("end-villain-phase-and-round", TranscriptStepKind.When,
            "the villain phase and round end", EndVillainPhaseAndRound),
        Bind("villain-damages-card", TranscriptStepKind.When,
            @"the villain deals (?<count>\d+) damage to card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            VillainDamagesCard),
        Bind("identity-defeated", TranscriptStepKind.When,
            @"seat (?<seat>\d+)'s identity is defeated", IdentityDefeated),
        Bind("change-form", TranscriptStepKind.When,
            @"seat (?<seat>\d+) changes form by flipping their identity", ChangeForm),
        Bind("inflict-status", TranscriptStepKind.When,
            @"an ability (?<action>stuns|confuses) card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            InflictStatus),
        Bind("card-deals-damage", TranscriptStepKind.When,
            @"card (?<source>\d+[a-z]?) copy (?<sourceCopy>\d+) deals (?<count>\d+) damage to card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            CardDealsDamage),
        Bind("place-threat", TranscriptStepKind.When,
            @"(?<count>\d+) threat is placed on card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            PlaceThreat),
        Bind("remove-threat", TranscriptStepKind.When,
            @"(?<count>\d+) threat is removed from card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            RemoveThreat),
        Bind("basic-attack", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses their basic attack against card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            BasicAttack),
        Bind("begin-basic-attack", TranscriptStepKind.When,
            @"seat (?<seat>\d+) begins their basic attack against card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            BeginBasicAttack),
        Bind("basic-attack-accepting-paid", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses their basic attack against card (?<face>\d+[a-z]?) copy (?<copy>\d+) and accepts ""(?<label>[^""]+)"" targeting card (?<target>\d+[a-z]?) copy (?<targetCopy>\d+) paid with card (?<payment>\d+[a-z]?) copy (?<paymentCopy>\d+)",
            BasicAttackAcceptingWithPayment),
        Bind("basic-attack-accepting-paid-no-target", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses their basic attack against card (?<face>\d+[a-z]?) copy (?<copy>\d+) and accepts ""(?<label>[^""]+)"" paid with card (?<payment>\d+[a-z]?) copy (?<paymentCopy>\d+)",
            BasicAttackAcceptingWithPaymentWithoutTarget),
        Bind("basic-thwart", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses their basic thwart against card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            BasicThwart),
        Bind("basic-recovery", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses their basic recovery",
            BasicRecovery),
        Bind("ally-power", TranscriptStepKind.When,
            @"card (?<ally>\d+[a-z]?) copy (?<allyCopy>\d+) uses its basic (?<power>attack|thwart) against card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            AllyPower),
        Bind("begin-ally-power", TranscriptStepKind.When,
            @"card (?<ally>\d+[a-z]?) copy (?<allyCopy>\d+) begins its basic (?<power>attack|thwart) against card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            BeginAllyPower),
        Bind("ally-power-accepting", TranscriptStepKind.When,
            @"card (?<ally>\d+[a-z]?) copy (?<allyCopy>\d+) uses its basic (?<power>attack|thwart) against card (?<face>\d+[a-z]?) copy (?<copy>\d+) and accepts the (?<label>.+) opportunity",
            AllyPowerAccepting),
        Bind("basic-attack-targets", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks for their basic attack targets",
            BasicAttackTargets),
        Bind("basic-thwart-targets", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks for their basic thwart targets",
            BasicThwartTargets),
        Bind("basic-recovery-availability", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks whether basic recovery is available",
            BasicRecoveryAvailability),
        Bind("villain-phase-decline", TranscriptStepKind.When,
            @"villain phase (?<round>\d+) resolves with every optional choice declined",
            ResolveVillainPhase),
        Bind("villain-phase-until-required", TranscriptStepKind.When,
            @"villain phase (?<round>\d+) resolves with every optional choice declined until a required decision",
            ResolveVillainPhaseUntilRequired),
        Bind("villain-phase-opportunity", TranscriptStepKind.When,
            @"villain phase (?<round>\d+) resolves accepting ""(?<label>[^""]+)""",
            ResolveVillainPhaseAccepting),
        Bind("villain-phase-paid-opportunity", TranscriptStepKind.When,
            @"villain phase (?<round>\d+) resolves accepting ""(?<label>[^""]+)"" paid with card (?<face>\d+[a-z]?) copy (?<copy>\d+)",
            ResolveVillainPhaseAcceptingWithPayment),
        Bind("villain-phase-defender", TranscriptStepKind.When,
            @"villain phase (?<round>\d+) resolves with card (?<face>\d+[a-z]?) copy (?<copy>\d+) defending the first attack",
            ResolveVillainPhaseWithDefender),
        Bind("villain-attack-defender", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) with card (?<face>\d+[a-z]?) copy (?<copy>\d+) defending",
            ResolveVillainAttackWithDefender),
        Bind("villain-attack-decline", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) with every optional choice declined",
            ResolveVillainAttack),
        Bind("villain-attack-until-required", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) with every optional choice declined until a required decision",
            ResolveVillainAttackUntilRequired),
        Bind("enemy-attack-decline", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) attacks seat (?<seat>\d+) with every optional choice declined",
            ResolveEnemyAttack),
        Bind("enemy-attack-until-required", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) attacks seat (?<seat>\d+) with every optional choice declined until a required decision",
            ResolveEnemyAttackUntilRequired),
        Bind("enemy-attack-defender", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) attacks seat (?<seat>\d+) with card (?<defender>\d+[a-z]?) copy (?<defenderCopy>\d+) defending",
            ResolveEnemyAttackWithDefender),
        Bind("villain-scheme-decline", TranscriptStepKind.When,
            @"the villain schemes against seat (?<seat>\d+) with every optional choice declined",
            ResolveVillainScheme),
        Bind("villain-attack-defender-opportunity", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) accepting ""(?<label>[^""]+)"" with card (?<face>\d+[a-z]?) copy (?<copy>\d+) defending",
            ResolveVillainAttackWithDefenderAndOpportunity),
        Bind("villain-attack-opportunity", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) accepting ""(?<label>[^""]+)""",
            ResolveVillainAttackWithOpportunity),
        Bind("villain-attack-two-opportunities", TranscriptStepKind.When,
            @"the villain attacks seat (?<seat>\d+) accepting ""(?<first>[^""]+)"" then ""(?<second>[^""]+)""",
            ResolveVillainAttackWithTwoOpportunities),
        Bind("minion-enters-play", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) enters play as a minion engaged with seat (?<seat>\d+)",
            MinionEntersPlay),
        Bind("support-enters-play", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) enters play as a support controlled by seat (?<seat>\d+)",
            SupportEntersPlay),
        Bind("upgrade-enters-play", TranscriptStepKind.When,
            @"card (?<face>\d+[a-z]?) copy (?<copy>\d+) enters play as an upgrade controlled by seat (?<seat>\d+)",
            UpgradeEntersPlay),
        Bind("request-printed-characteristics", TranscriptStepKind.When,
            @"the printed characteristics of card (?<face>\d+[a-z]?) copy (?<copy>\d+) are requested",
            RequestPrintedCharacteristics),
        Bind("initiate-action-with-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) initiates card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s action paying with these cards",
            InitiateActionWithPayment),
        Bind("initiate-action-without-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) initiates card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s action without payment",
            InitiateActionWithoutPayment),
        Bind("initiate-action-with-discard", TranscriptStepKind.When,
            @"seat (?<seat>\d+) initiates card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s action discarding these cards",
            InitiateActionWithDiscard),
        Bind("initiate-indexed-action-with-variable", TranscriptStepKind.When,
            @"seat (?<seat>\d+) initiates card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s (?<ordinal>first|second) printed action defining X as (?<value>\d+) paying with these cards",
            InitiateIndexedActionWithVariable),
        Bind("initiate-indexed-action-without-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) initiates card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s (?<ordinal>first|second) printed action without payment",
            InitiateIndexedActionWithoutPayment),
        Bind("play-card-with-target-and-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) plays card (?<face>\d+[a-z]?) copy (?<copy>\d+) targeting card (?<target>\d+[a-z]?) copy (?<targetCopy>\d+) paying with these cards",
            PlayCardWithTargetAndPayment),
        Bind("play-card-with-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) plays card (?<face>\d+[a-z]?) copy (?<copy>\d+) paying with these cards",
            PlayCardWithPayment),
        Bind("request-card-actions", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks for available card actions",
            RequestCardActions),
        Bind("use-card-resource-ability", TranscriptStepKind.When,
            @"seat (?<seat>\d+) uses card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s resource ability",
            UseCardResourceAbility),
        Bind("request-turn-card-actions", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks for card actions available during their turn",
            RequestTurnCardActions),
        Bind("inspect-core-scene", TranscriptStepKind.When,
            "the dealt Core scene is inspected", InspectCoreScene),
        Bind("begin-mulligan", TranscriptStepKind.When,
            @"game setup reaches seat (?<seat>\d+)'s mulligan", BeginMulligan),
        Bind("resolve-mulligan", TranscriptStepKind.When,
            @"seat (?<seat>\d+) mulligans these cards", ResolveMulligan),
        Bind("keep-mulligan", TranscriptStepKind.When,
            @"seat (?<seat>\d+) keeps every opening-hand card at mulligan",
            KeepMulligan),
        Bind("end-player-turn", TranscriptStepKind.When,
            @"seat (?<seat>\d+) ends their turn",
            EndPlayerTurn),
        Bind("request-voluntary-form-change", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks whether a voluntary form change is available",
            RequestVoluntaryFormChange),
        Bind("request-card-play", TranscriptStepKind.When,
            @"seat (?<seat>\d+) asks whether card (?<face>\d+[a-z]?) copy (?<copy>\d+) is available to play",
            RequestCardPlay),
        Bind("take-voluntary-form-change", TranscriptStepKind.When,
            @"seat (?<seat>\d+) takes their voluntary form change",
            TakeVoluntaryFormChange),
        Bind("choose-setup-card", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses card (?<face>\d+[a-z]?) copy (?<copy>\d+) for the pending setup ability",
            ChooseSetupCard),
        Bind("choose-pending-card", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses card (?<face>\d+[a-z]?) copy (?<copy>\d+) for the pending action",
            ChoosePendingCard),
        Bind("choose-pending-cards", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses these cards for the pending action",
            ChoosePendingCards),
        Bind("order-pending-cards", TranscriptStepKind.When,
            @"seat (?<seat>\d+) orders these cards for the pending action",
            OrderPendingCards),
        Bind("choose-pending-card-and-discard", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses card (?<face>\d+[a-z]?) copy (?<copy>\d+) and discards these cards for the pending action",
            ChoosePendingCardAndDiscard),
        Bind("choose-pending-card-with-payment", TranscriptStepKind.When,
            @"seat (?<seat>\d+) chooses card (?<face>\d+[a-z]?) copy (?<copy>\d+) paying with these cards for the pending action",
            ChoosePendingCardWithPayment),
        Bind("accept-pending-opportunity", TranscriptStepKind.When,
            @"seat (?<seat>\d+) accepts the ""(?<label>[^""]+)"" pending opportunity",
            AcceptPendingOpportunity),
        Bind("accept-card-pending-opportunity", TranscriptStepKind.When,
            @"seat (?<seat>\d+) accepts card (?<face>\d+[a-z]?) copy (?<copy>\d+)'s pending opportunity",
            AcceptCardPendingOpportunity),
        Bind("decline-pending-opportunity", TranscriptStepKind.When,
            @"seat (?<seat>\d+) declines the pending opportunity",
            DeclinePendingOpportunity),
    ];
}
