<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Marvel.Rules.Packs.Harvest</RootNamespace>
    <AssemblyName>Marvel.Rules.Packs.Harvest</AssemblyName>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../../tests/Shared/RepositoryPaths.cs" Link="RepositoryPaths.cs" />
  </ItemGroup>

</Project>
