import os

class MimeType:
    mime_types = {
        '.txt': 'text/plain',
        '.pdf': 'application/pdf',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.png': 'image/png',
        '.gif': 'image/gif',
        '.html': 'text/html',
        '.css': 'text/css',
        '.js': 'application/javascript',
        '.json': 'application/json',
        '.xml': 'application/xml',
        '.csv': 'text/csv',
        '.zip': 'application/zip',
        '.tar': 'application/x-tar',
        '.gz': 'application/gzip',
        '.mp3': 'audio/mpeg',
        '.wav': 'audio/wav',
        '.mp4': 'video/mp4',
        '.avi': 'video/x-msvideo',
        '.mov': 'video/quicktime',
        '.svg': 'image/svg+xml',
        '.bmp': 'image/bmp',
        '.webp': 'image/webp',
        '.ico': 'image/x-icon',
        '.ai': 'application/postscript',
        '.apk': 'application/vnd.android.package-archive',
        '.bat': 'application/x-msdownload',
        '.bin': 'application/octet-stream',
        '.c': 'text/x-c',
        '.class': 'application/java-vm',
        '.cpp': 'text/x-c++',
        '.doc': 'application/msword',
        '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        '.exe': 'application/x-msdownload',
        '.flac': 'audio/flac',
        '.gif': 'image/gif',
        '.html': 'text/html',
        '.jar': 'application/java-archive',
        '.json': 'application/json',
        '.key': 'application/vnd.apple.keynote',
        '.m4a': 'audio/mp4',
        '.md': 'text/markdown',
        '.odt': 'application/vnd.oasis.opendocument.text',
        '.ppt': 'application/vnd.ms-powerpoint',
        '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        '.psd': 'application/vnd.adobe.photoshop',
        '.rar': 'application/x-rar-compressed',
        '.rtf': 'application/rtf',
        '.sh': 'application/x-sh',
        '.sql': 'application/sql',
        '.svg': 'image/svg+xml',
        '.tar.gz': 'application/gzip',
        '.tex': 'application/x-tex',
        '.tiff': 'image/tiff',
        '.ts': 'video/mp2t',
        '.woff': 'font/woff',
        '.woff2': 'font/woff2',
        '.xls': 'application/vnd.ms-excel',
        '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        '.xml': 'application/xml',
        '.yaml': 'text/yaml',
        '.zip': 'application/zip',
    }

    @staticmethod
    def GetMimeType(file_path: str) -> str:
        """Return the MIME type for the given file path."""
        _, ext = os.path.splitext(file_path)
        return MimeType.mime_types.get(ext.lower(), 'application/octet-stream')  # Default MIME type

